---
# tasks file for role
#
- name: install krb5 packages
  package:
    name: "{{ krb5_packages }}"
    state: present
  tags: [ krb5 ]
  when: krb5_configure == True

- name: update /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '644'
  tags: [ krb5 ]
  when: krb5_configure == True
